name: WG Easy Docker Image CI

on:
  workflow_dispatch:

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repo
        uses: actions/checkout@v3

      - name: Set Path
        run: |
          echo "REPO_NAME=wg-easy" >> $GITHUB_ENV

      - name: Get Package Version
        run: |
          VER=$(cat ./${{ env.REPO_NAME }}/VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: 'docker.io'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: github.event_name != 'pull_request'
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.VERSION }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./${{ env.REPO_NAME }}
          file: ./${{ env.REPO_NAME }}/Dockerfile
          platforms: linux/amd64, linux/arm/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
